targets:
  $default:
    builders:
      #drift @DriftDatabase()
      drift_dev:
        # Disable default builder to use modular builder instead
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &drift_options
          store_date_time_values_as_text: true
          named_parameters: true
          write_from_json_string_constructor: false
          data_class_to_companions: false
          skip_verification_code: true
        generate_for: &drift_generate_for
          - lib/domain/entities/*.dart
          - lib/domain/repositories/database.repository.dart
      drift_dev:modular:
        enabled: true
        options: *drift_options
        generate_for: *drift_generate_for
      #autoroute @RoutePage()
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/**.page.dart
      #autoroute @AutoRouterConfig()
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/presentation/router/router.dart
      #localization
      slang_build_runner:
        options:
          fallback_strategy: base_locale_empty_string
          input_directory: assets/i18n
          output_directory: lib/i18n
          timestamp: false
