name: immich_mobile
description: Immich - selfhosted backup media file on mobile phone

publish_to: 'none'
version: 1.102.0+132

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Platform related
  path_provider: ^2.1.4
  path: ^1.9.0
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  # State handling
  flutter_bloc: ^8.1.6
  # Database
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  # Network
  http: ^1.2.2
  # Route handling
  auto_route: ^9.2.2
  # Logging
  logging: ^1.2.0
  # Collection Utils
  collection: ^1.18.0
  # service_locator
  get_it: ^7.7.0
  # Photo Manager
  photo_manager: ^3.3.0
  photo_manager_image_provider: ^2.1.1
  # Localization
  intl: ^0.19.0
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  # oauth login
  flutter_web_auth_2: ^3.1.2
  # components
  material_symbols_icons: ^4.2785.1
  flutter_adaptive_scaffold: ^0.3.1
  flutter_list_view: ^1.1.28
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  openapi:
    path: openapi

dependency_overrides:
  # openapi uses an older version of http for backward compatibility. New versions do not have
  # a breaking change so it is safer to override it and use the latest version for the app
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^4.0.0
  # Code generator
  build_runner: ^2.4.12
  # Database helper
  drift_dev: ^2.20.3
  # Route helper
  auto_route_generator: ^9.0.0
  # Localization generator
  slang_build_runner: ^3.31.0
  # Assets constant generator
  flutter_gen_runner: ^5.7.0
  # Type safe platform channels
  pigeon: ^22.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/utils/constants/
